# Generated by Django 4.1 on 2022-08-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('study_field', models.CharField(max_length=200)),
                ('scholarship_name', models.CharField(max_length=200)),
                ('scholarship_system', models.CharField(max_length=200)),
                ('scholarships_available', models.CharField(max_length=200)),
                ('start_convocatory', models.CharField(max_length=200)),
                ('end_convocatory', models.CharField(max_length=200)),
                ('results_selected_day', models.CharField(max_length=200)),
                ('start_scholarship', models.CharField(max_length=200)),
                ('end_scholarship', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'universities',
            },
        ),
    ]
