# Generated by Django 4.1 on 2022-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=200)),
                ('study_field', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('scope_field', models.CharField(max_length=200)),
                ('scholarship_system', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'scholars',
            },
        ),
    ]
